# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  # Path to the directory containing conf.py relative to the root of the project
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"
# Optionally declare the formats of your documentation
formats:
  - html
  - pdf

# Optionally configure the build process
build:
  image: latest  # Use the latest build image for the most up-to-date tools

