# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  # Path to the directory containing conf.py relative to the root of the project
  configuration: docs/conf.py

# Set the version of Python
python:
  version: 3.11

# Optionally define how Read the Docs will install your project
# python:
#   install:
#     - requirements: docs/requirements.txt

# Declare the formats of your documentation
formats:
  - html
  - pdf

# Configure the build process
build:
  # Omit the `os` configuration, it's not needed here
  image: latest  # Use the latest build image for the most up-to-date tools


